### ISSUE TITLE
Include main-built.js in the template and/or spawn optimizer automatically

### ISSUE THREAD

**Issue by xqiu** [johnpapa/HotTowel#1]
We should include main-built.js in the template to allow the full end to end story including project deployment directly from VS.  

If we can even have an after build event to automatic spawn Durandal optimizer.exe , it will be even better.

**Comment by johnpapa** [comment]
Hottowel is a starting place, not the end of the project. Once you add anything to the project the main-built is obsolete and has to be generated again. It is best to keep it as-is and leave the comment in place to remind the developer to generate the optimized code when it is needed (at the end of the project)
