### ISSUE TITLE
Error: AngularJS-Modular-Demo

### ISSUE THREAD

**Issue by XenCloete** [johnpapa/HotTowel#21]
npm install error. Please let me know what I can do to resolve this. Thanks, Xen

173007 verbose unsafe-perm in lifecycle true
173008 info AngularJS-Modular-Demo@0.0.1 Failed to exec install script
173009 error AngularJS-Modular-Demo@0.0.1 install: `bower install`
173009 error Exit status 1
173010 error Failed at the AngularJS-Modular-Demo@0.0.1 install script.
173010 error This is most likely a problem with the AngularJS-Modular-Demo package,
173010 error not with npm itself.
173010 error Tell the author that this fails on your system:
173010 error     bower install
173010 error You can get their info via:
173010 error     npm owner ls AngularJS-Modular-Demo
173010 error There is likely additional logging output above.
173011 error System Windows_NT 6.2.9200
173012 error command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
173013 error cwd C:\play
173014 error node -v v0.10.33
173015 error npm -v 1.4.28
173016 error code ELIFECYCLE

**Comment by johnpapa** [comment]
this is a nuget package, not npm.

**Comment by XenCloete** [comment]
Thank you for the reply. My apologies for being slow. ;)
