### ISSUE TITLE
Durandal viewmodel routing

### ISSUE THREAD

**Issue by mattjohnsonpint** [johnpapa/HotTowel#4]
Out of the box, the only routes that exist in shell.js are:

```
router.mapNav('home');
router.mapNav('details');
```

If you add new views/viemodels, you have to go add them to shell.js.

It would be a lot more useful if you changed it to:

```
router.mapAuto('viewmodels');
router.mapNav('home');
router.mapNav('details');
```

So that any new views/viewmodels that are added are picked up automatically.

Even better would be to have an array somewhere of the routes that are visible in the navigation

```
var navRoutes = ['home','details'];
```

Then just call mapNav on the routes in that array.

**Comment by johnpapa** [comment]
The idea of the template is to show how to do it yourself. The  2 examples make it clear how to add more. You can certainly create an array and add more too. I'm not a fan of mapAuto as its a bit too much magic for me, and it doesn't show someone how to deviate from it. 

All the ways you show are valid, but the concept oif the template is to give a starting point you can build on. And it does that well as-is.
