### ISSUE TITLE
Q has a nuget now

### ISSUE THREAD

**Issue by mattjohnsonpint** [johnpapa/HotTowel#8]
Hi John.  You can update your next HotTowel nuspec to include Q.

https://nuget.org/packages/q

https://github.com/kriskowal/q/issues/222

Cheers!

**Comment by johnpapa** [comment]
Neat. It's part of Breeze, so they should depend on this. HotTowel would update when Breeze updates. I let them know. Thanks.

**Comment by mattjohnsonpint** [comment]
Ah - I was wondering why I didn't see it used much. :)

BTW - I have also authorization hooked in via DNOA / OAuthWebSecurity (ala the other MVC4 templates).  At some point I will genericize it and send you a pull req or post it as a separate add on.

**Comment by johnpapa** [comment]
No worries.

I dont think I'll put auth in this template. Make the pull request, and I'll look, but I really want to keep this bare bones as not everyone wants the same kind of auth.

**Comment by mattjohnsonpint** [comment]
ok.  I'll just plan on it being an add-on then.  Or maybe just a fork that people can look at if they want to know how to do it themselves.

**Comment by johnpapa** [comment]
add on is not a bad idea!

John Papa | @john_papa | JohnPapa.net, LLC
