### ISSUE TITLE
Kendo UI Doesn't Integrate Well With Durandal

### ISSUE THREAD

**Issue by breynolds** [johnpapa/HotTowel#9]
Kendo UI is important to us, but it doesn't integrate well with Durandal. Apparently there is a fix coming sometime soon. It would be VERY helpful to pick up this Durandal fix:

https://github.com/BlueSpire/Durandal/issues/74

**Comment by rgullhaug** [comment]
I have written a blog post on how to get Durandal and Kendo UI to play nice together. You can find it here: http://rgullhaug.wordpress.com/2013/03/06/using-durandal-and-kendoui-together/

**Comment by johnpapa** [comment]
The next version of Hot Towel will include the 1.2 of Durandal, which has this fix.
